image: python:3.12

stages:
  - test-deps
  - pages

before_script:
  - wget -qO- https://astral.sh/uv/install.sh | sh
  - source $HOME/.local/bin/env
  - uv venv
  - uv pip install .[dev]

test-deps:
  stage: test-deps
  script:
    - uv sync --upgrade --all-extras

run-tests:
  stage: test-deps
  script:
    - uv run pytest

pages:
  stage: pages
  script:
  - uv run mkdocs build --strict --verbose
  - mv site public
  artifacts:
    paths:
    - public
  only:
    - main
    
