image: python:3.12

stages:
  - test-deps
  - pages

before_script:
  - pip install poetry
  - poetry install -E dev
  - source `poetry env info --path`/bin/activate

test-deps:
  stage: test-deps
  script:
    - poetry update

pages:
  stage: pages
  script:
  - poetry run mkdocs build --strict --verbose
  - mv site public
  artifacts:
    paths:
    - public
  only:
    - main
    
