site_name: 'Fragment Bot Documentation'

repo_name: 'glass-ships/fragment-bot'
repo_url: 'https://gitlab.com/glass-ships/fragment-bot'

docs_dir: docs/

nav: 
    - Home: 'index.md'
    - Commands: 'commands/general.md'

theme:
    name: 'material'
    features:
        - navigation.expand
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
