site_name: 'Compass Bot Documentation'

repo_name: 'glass-ships/compass-bot'
repo_url: 'https://gitlab.com/glass-ships/compass-bot'

theme:
    name: 'material'
    docs_dir: docs/
    logo: 'images/compassBkgd.png'
    favicon:
        'images/favicon.ico'
    features:
        - navigation.expand
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
    palette:
        scheme: 'slate'
        primary: 'indigo'
        accent: 'cyan'
    font:
        text: 'Roboto'
        #code: 'Fira Mono'

extra:
  social:
    - icon: 'fontawesome/solid/house'
      link: 'https://glass-ships.com'
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/glass-ships'
    #- icon: 'fontawesome/brands/twitter'
    #  link: 'https://twitter.com/'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - attr_list
  - pymdownx.betterem:
      smart_enable: all


copyright: 'Copyright &copy; 2020 - 2022 Glass (contact@glass-ships.com)'
